server:
  port: 8206

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.zero.yianyx.enums

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shequ-user?characterEncoding=utf-8&useSSL=false
    username: root
    password: zero

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 192.168.200.155
    port: 6379
    database: 0
    timeout: 1800000
    password: 780415
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 8
        min-idle: 0
wx:
  open:
    #小程序id
    app_id: wxc94eddd3fd727146
    #小程序密钥
    app_secret: 4d8e67395acf92ef529b28143b4a251a


logging:
  level:
    com.zero.yianyx: debug
